apiVersion: v1
kind: Service
metadata:
  name: restaurant-listing-service-service
spec:
  selector:
    app: restaurant-listing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
